// Reads taxonomy.js and regenerates:
//   1. subjects.json                                  (engine reads this if the DB is empty)
//   2. supabase/migrations/20260706190100_seed_subjects.sql  (DB source of truth)
// Run: npm run build:seed
const fs = require("fs");
const path = require("path");
const taxonomy = require("./taxonomy");

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const rows = [];
const seen = new Set();
let order = 0;
for (const [domain, subjects] of Object.entries(taxonomy)) {
  for (const name of subjects) {
    let slug = slugify(name);
    // Guarantee uniqueness (rare cross-domain name collisions).
    let candidate = slug;
    let n = 2;
    while (seen.has(candidate)) candidate = `${slug}-${n++}`;
    slug = candidate;
    seen.add(slug);
    order += 1;
    rows.push({ slug, name, domain, sort_order: order });
  }
}

const domains = Object.keys(taxonomy).length;
const counts = Object.values(taxonomy).map((s) => s.length);
if (new Set(counts).size > 1) {
  console.warn(`Warning: domains have uneven subject counts: ${counts.join(", ")}`);
}

// 1. subjects.json
fs.writeFileSync(path.join(__dirname, "subjects.json"), JSON.stringify(rows, null, 2) + "\n");

// 2. seed migration
const sqlEsc = (s) => s.replace(/'/g, "''");
const values = rows
  .map((r) => `  ('${r.slug}', '${sqlEsc(r.name)}', '${sqlEsc(r.domain)}', ${r.sort_order})`)
  .join(",\n");
const sql = `-- Generated by question-curator/build-seed.js from taxonomy.js. Do not edit by hand;
-- edit taxonomy.js and re-run \`npm run build:seed\`. ${rows.length} subjects.
insert into public.subjects (slug, name, domain, sort_order) values
${values}
on conflict (slug) do update set
  name = excluded.name, domain = excluded.domain, sort_order = excluded.sort_order;
`;
const outPath = path.join(__dirname, "..", "supabase", "migrations", "20260706190100_seed_subjects.sql");
fs.writeFileSync(outPath, sql);

console.log(`Wrote ${rows.length} subjects across ${domains} domains.`);
console.log(`  - ${path.relative(process.cwd(), path.join(__dirname, "subjects.json"))}`);
console.log(`  - ${path.relative(process.cwd(), outPath)}`);
