// The subject taxonomy: 25 domains x 40 subjects = 1000 subjects.
// Edit this file to change the subject bank, then run `npm run build:seed` to
// regenerate subjects.json and the Supabase seed migration.

module.exports = {
  "World History": [
    "Ancient Egypt", "The Roman Empire", "Ancient Greece", "Medieval Europe",
    "The Renaissance", "World War I", "World War II", "The Cold War",
    "Ancient China", "The Ottoman Empire", "The French Revolution",
    "The American Revolution", "The Industrial Revolution", "Ancient Mesopotamia",
    "The Vikings", "The British Empire", "Feudal Japan", "The Mongol Empire",
    "Pre-Columbian Americas", "The Age of Exploration",
    "The Byzantine Empire", "The Crusades", "Colonial Africa", "The Aztec Empire",
    "The Inca Empire", "Ancient Persia", "The Protestant Reformation",
    "The Napoleonic Wars", "The Space Race", "The Berlin Wall", "Decolonization",
    "The Silk Road", "Ancient Sumer", "The Hanseatic League",
    "The Meiji Restoration", "The Partition of India", "The Warsaw Pact",
    "Colonial America", "The Gilded Age", "The Interwar Period",
  ],
  "Science & Nature": [
    "Classical Physics", "Quantum Mechanics", "The Periodic Table",
    "Chemical Reactions", "Genetics & DNA", "Evolution", "Cell Biology",
    "Thermodynamics", "Electricity & Magnetism", "Optics & Light",
    "Nuclear Physics", "Organic Chemistry", "Ecology", "Photosynthesis",
    "The Scientific Method", "Famous Scientists", "Nobel Prize Discoveries",
    "States of Matter", "Waves & Sound", "Forces & Motion",
    "Astrophysics", "Marine Biology", "Meteorology", "Geophysics",
    "Biochemistry", "Immunology", "Microbiology", "Paleontology",
    "Volcanology", "Seismology", "Botany", "Zoology", "Particle Physics",
    "Materials Science", "Climate Science", "Entomology", "Mycology",
    "Astrobiology", "Environmental Science", "Physical Chemistry",
  ],
  "Geography": [
    "World Capitals", "Rivers of the World", "Mountain Ranges", "Oceans & Seas",
    "Deserts", "World Flags", "Countries of Africa", "Countries of Asia",
    "Countries of Europe", "Countries of the Americas", "Islands & Archipelagos",
    "Volcanoes", "National Parks", "U.S. States", "Borders & Boundaries",
    "Lakes of the World", "Climate Zones", "Time Zones", "Cartography & Maps",
    "Population & Cities",
    "Tectonic Plates", "Archipelago Nations", "World Canals", "Highest Peaks",
    "Longest Rivers", "Largest Deserts", "Coastlines of the World",
    "Continental Divides", "World Wetlands", "Territorial Disputes",
    "Exclaves & Enclaves", "Geographic Extremes", "World Plateaus", "Fjords",
    "Isthmuses", "Equatorial Countries", "Polar Geography", "Map Projections",
    "Geography of Asia", "Geography of Africa",
  ],
  "Literature": [
    "Shakespeare", "Greek Classics", "19th-Century Novels", "Modernist Literature",
    "Poetry", "Science Fiction Books", "Fantasy Literature",
    "Detective & Mystery Fiction", "Nobel Laureates in Literature",
    "Children's Literature", "Russian Literature", "American Literature",
    "British Literature", "Dystopian Fiction", "Epic Poetry", "Literary Characters",
    "Opening Lines & Passages", "Banned Books", "Pulitzer & Booker Winners",
    "Playwrights & Drama",
    "Gothic Novels", "The Beat Generation", "Magical Realism",
    "Postmodern Literature", "Victorian Literature", "African Literature",
    "Latin American Literature", "Graphic Novels", "Young Adult Fiction",
    "Epistolary Novels", "Satire in Literature", "War Literature",
    "Travel Writing", "Literary Awards", "Short Story Masters",
    "Memoirs & Autobiographies", "Classical Epics", "Absurdist Fiction",
    "Feminist Literature", "Historical Fiction",
  ],
  "Film & Cinema": [
    "Classic Hollywood", "Oscar Best Pictures", "Film Directors", "Film Noir",
    "Animated Films", "Science Fiction Films", "Horror Films", "Movie Quotes",
    "Blockbuster Franchises", "Foreign Language Films", "The Silent Film Era",
    "Documentary Films", "Movie Soundtracks", "Special Effects & VFX",
    "Cult Classics", "Film Festivals", "Actors & Actresses", "Superhero Movies",
    "Westerns", "Movies by Decade",
    "Film Editing", "Cinematography", "Movie Musicals", "Heist Films",
    "War Films", "Courtroom Dramas", "Road Movies", "Biopics", "Film Scores",
    "Independent Cinema", "Bollywood", "Korean Cinema", "French New Wave",
    "Movie Trilogies", "Cult Directors", "Movie Remakes", "Screenwriting",
    "Movie Posters", "Practical Effects", "Movie Villains",
  ],
  "Music": [
    "Classical Composers", "The Beatles", "Rock & Roll", "Jazz", "Hip-Hop",
    "Pop Music", "Country Music", "Opera", "Music Theory", "Musical Instruments",
    "Electronic Music", "Grammy Awards", "Music of the 1980s", "Reggae", "Blues",
    "Folk Music", "Broadway & Musicals", "Album Covers", "One-Hit Wonders",
    "World Music",
    "Music Festivals", "Music Producers", "Punk Rock", "Heavy Metal", "Disco",
    "Ska Music", "Choral Music", "Symphony Orchestras", "Music Sampling",
    "Vinyl Records", "Concept Albums", "Musical Notation", "Song Lyrics",
    "Music Videos", "Record Labels", "Live Concerts", "A Cappella",
    "Gospel Music", "Latin Music", "Indie Rock",
  ],
  "Sports": [
    "The Olympic Games", "Association Football", "Basketball", "American Football",
    "Baseball", "Tennis", "Golf", "Cricket", "Formula 1", "Boxing",
    "The FIFA World Cup", "Ice Hockey", "Rugby", "Athletics & Track", "Swimming",
    "Cycling", "Martial Arts", "Winter Sports", "Sports Records",
    "Sports Halls of Fame",
    "Table Tennis", "Badminton", "Volleyball", "Handball", "Wrestling",
    "Weightlifting", "Archery", "Fencing", "Rowing", "Sailing", "Skiing",
    "Snowboarding", "Surfing", "Skateboarding", "Gymnastics", "Triathlon",
    "Marathon Running", "Paralympic Sports", "Sports Sponsorships",
    "Sports Injuries",
  ],
  "Art & Architecture": [
    "Renaissance Art", "Impressionism", "Modern Art", "Famous Paintings",
    "Sculpture", "Gothic Architecture", "Ancient Architecture", "Surrealism",
    "Photography", "Pop Art", "Baroque Art", "Street Art", "Architectural Styles",
    "Famous Museums", "Cubism", "Art Movements", "Pottery & Ceramics",
    "Skyscrapers", "Bridges & Landmarks", "Color & Design",
    "Minimalism", "Abstract Expressionism", "Renaissance Sculpture",
    "Islamic Art", "African Art", "Asian Art", "Art Restoration", "Land Art",
    "Performance Art", "Art Forgeries", "Mosaics", "Stained Glass", "Frescoes",
    "Brutalist Architecture", "Art Deco", "Neoclassical Architecture",
    "Landscape Design", "Art Auctions", "Ceramics History", "Textile Art",
  ],
  "Technology & Computing": [
    "Computer History", "Programming Languages", "The Internet",
    "Artificial Intelligence", "Operating Systems", "Cybersecurity",
    "Social Media", "Smartphones", "Cryptography", "Video Game Consoles",
    "Tech Companies", "Hardware & Processors", "Databases", "Robotics",
    "The World Wide Web", "Open Source Software", "Silicon Valley",
    "Coding Concepts", "Computer Networking", "Cryptocurrency & Blockchain",
    "Quantum Computing", "Cloud Computing", "Data Science", "Machine Learning",
    "Virtual Reality", "Augmented Reality", "Wearable Tech", "3D Printing",
    "Semiconductor Manufacturing", "Internet Protocols",
    "Encryption Standards", "Software Development", "User Interface Design",
    "Tech Patents", "E-commerce Platforms", "Cloud Storage", "Computer Vision",
    "Natural Language Processing", "IT History Milestones", "Open Standards",
  ],
  "Food & Drink": [
    "World Cuisines", "Wine", "Cheese", "Coffee", "Spices & Herbs", "Desserts",
    "Cocktails", "Beer & Brewing", "Italian Cuisine", "French Cuisine",
    "Asian Cuisine", "Street Food", "Cooking Techniques", "Fruits & Vegetables",
    "Tea", "Baking & Pastry", "Fast Food", "Famous Chefs", "Food History",
    "Condiments & Sauces",
    "Mexican Cuisine", "Indian Cuisine", "Middle Eastern Cuisine",
    "Caribbean Cuisine", "African Cuisine", "Vegan Cooking",
    "Molecular Gastronomy", "Michelin Star Restaurants", "Food Trucks",
    "Farm-to-Table", "Regional American Cuisine", "Sushi",
    "Barbecue Traditions", "Bread & Baking", "Ice Cream", "Chocolate",
    "Honey & Beekeeping", "Food Preservation", "Culinary Schools",
    "Table Etiquette",
  ],
  "Television": [
    "Sitcoms", "Drama Series", "Reality TV", "Animated Series", "British TV",
    "Game Shows", "Sci-Fi & Fantasy TV", "Crime Dramas", "TV Comedies",
    "Streaming Originals", "Soap Operas", "Talk Shows", "TV Theme Songs", "Anime",
    "TV Catchphrases", "Emmy Winners", "Cartoon Classics", "Miniseries",
    "TV Hosts", "Television History",
    "Late-Night TV", "Children's Television", "Docuseries", "TV Pilots",
    "Cable News History", "Public Broadcasting", "TV Ratings",
    "Spin-off Shows", "TV Adaptations", "British Sitcoms", "Telenovelas",
    "Streaming Wars", "Puppet Shows", "TV Cliffhangers",
    "Live Television Events", "Reality Competition Shows",
    "TV Network History", "Dubbing & Localization", "TV Theme Composers",
    "Binge-Watching Culture",
  ],
  "Video Games": [
    "Nintendo", "PlayStation", "Retro Arcade Games", "Role-Playing Games",
    "First-Person Shooters", "Indie Games", "Esports", "Game Franchises",
    "Fighting Games", "Strategy Games", "Open-World Games", "The Mario Universe",
    "The Legend of Zelda", "Pokemon", "Minecraft", "Game Developers",
    "Gaming Hardware", "Puzzle Games", "MMORPGs", "Video Game Music",
    "Speedrunning", "Game Modding", "Virtual Reality Games", "Mobile Gaming",
    "Game Art & Design", "Battle Royale Games", "Sandbox Games",
    "Visual Novels", "Rhythm Games", "Racing Games", "Game Streaming",
    "Game Publishers", "Retro Consoles", "Handheld Consoles",
    "Multiplayer Online Games", "Game Speed Records", "Game Localization",
    "Early Computer Games", "Game Design Theory", "Gaming Conventions",
  ],
  "Mythology & Religion": [
    "Greek Mythology", "Norse Mythology", "Egyptian Mythology", "Roman Mythology",
    "World Religions", "Christianity", "Islam", "Hinduism", "Buddhism", "Judaism",
    "Celtic Mythology", "Japanese Folklore", "Legendary Creatures",
    "Biblical Stories", "Gods & Goddesses", "Sacred Texts", "Mythological Heroes",
    "Afterlife Beliefs", "Rituals & Festivals", "Creation Myths",
    "Aztec Mythology", "Mayan Mythology", "Slavic Mythology", "Hindu Epics",
    "Sikhism", "Shinto", "Zoroastrianism", "Taoism", "Confucianism", "Jainism",
    "Religious Architecture", "Religious Holidays", "Saints & Sainthood",
    "Angels & Demons", "Prophets", "Religious Reformation Movements",
    "Sacred Sites", "Pilgrimages", "Mythical Places", "Comparative Religion",
  ],
  "Politics & Law": [
    "World Leaders", "U.S. Presidents", "Political Systems", "The United Nations",
    "Constitutions", "Elections & Voting", "Supreme Court Cases",
    "International Treaties", "Human Rights", "Political Ideologies", "Monarchies",
    "Diplomacy", "Legal Systems", "Famous Trials", "Political Scandals",
    "Prime Ministers", "Revolutions & Movements", "Branches of Government",
    "Espionage", "Landmark Legislation",
    "International Law", "Criminal Law", "Civil Rights Movements",
    "Political Parties", "Referendums", "Federalism", "Impeachment",
    "Political Debates", "Lobbying", "Campaign Finance", "Voting Systems",
    "Political Cartoons", "War Crimes Tribunals", "Refugee Law",
    "Environmental Law", "Labor Law", "Constitutional Amendments",
    "Political Assassinations", "Coalition Governments",
    "Political Think Tanks",
  ],
  "Business & Economics": [
    "Stock Markets", "Famous Entrepreneurs", "Global Brands", "Economic Theory",
    "Currencies", "Marketing & Advertising", "Startups", "Banking",
    "Trade & Commerce", "Fortune 500 Companies", "Supply & Demand",
    "Inflation & Recession", "Corporate Logos", "Billionaires",
    "Management & Leadership", "Real Estate", "Mergers & Acquisitions",
    "Retail & Shopping", "Economic History", "Personal Finance",
    "Venture Capital", "Cryptocurrency Markets", "Mergers in Tech",
    "Antitrust Law", "Labor Unions", "Franchise Businesses",
    "Advertising History", "Business Ethics", "Corporate Governance",
    "Trade Wars", "Manufacturing Industry", "Retail Giants",
    "Insurance Industry", "International Trade Agreements",
    "Economic Indicators", "Stock Exchanges", "Consumer Behavior",
    "Business Bankruptcies", "Nonprofit Organizations", "Family Businesses",
  ],
  "Space & Astronomy": [
    "The Solar System", "The Planets", "Stars & Constellations", "Galaxies",
    "Space Missions", "The Moon", "Black Holes", "The Sun", "Astronauts",
    "Telescopes", "Comets & Asteroids", "NASA", "The Big Bang", "Exoplanets",
    "Rockets & Spaceflight", "Mars Exploration", "The Space Station", "Cosmology",
    "Nebulae", "Space Agencies",
    "Space Telescopes", "Interstellar Travel Concepts", "Dwarf Planets",
    "Astrophysics Discoveries", "International Space Cooperation",
    "Rocket Engines", "Satellites", "Space Tourism", "Lunar Missions",
    "Mars Rovers", "Solar Flares", "Meteor Showers", "Astronomical Instruments",
    "Space Debris", "Habitable Zones", "Space Suits", "Cosmic Radiation",
    "Space Law", "Observatories", "Amateur Astronomy",
  ],
  "Animals & Wildlife": [
    "Mammals", "Birds", "Reptiles & Amphibians", "Fish & Marine Life", "Insects",
    "Dinosaurs", "Endangered Species", "Big Cats", "Primates", "Ocean Predators",
    "Pets & Domestic Animals", "Animal Behavior", "Migration & Hibernation",
    "Rainforest Animals", "Polar Wildlife", "Venomous Animals",
    "Animal Classification", "Extinct Animals", "Deep Sea Creatures",
    "Wildlife Conservation",
    "Camouflage in Nature", "Animal Intelligence", "Pack Animals",
    "Nocturnal Animals", "Desert Animals", "Grassland Animals",
    "Domestication History", "Animal Sounds", "Animal Symbiosis",
    "Keystone Species", "Invasive Species", "Animal Longevity",
    "Herbivores & Carnivores", "Animal Communication", "Zoos & Sanctuaries",
    "Wildlife Photography", "Animal Adaptations", "Cold-Blooded Animals",
    "Working Animals", "Coral Reef Ecosystems",
  ],
  "Human Body & Medicine": [
    "Human Anatomy", "The Circulatory System", "The Nervous System",
    "The Immune System", "Diseases & Disorders", "Vaccines", "Medical History",
    "Surgery", "Pharmacology", "Nutrition", "The Brain", "Genetics & Heredity",
    "Bones & Skeleton", "The Digestive System", "Mental Health", "Pandemics",
    "Famous Physicians", "Blood & Blood Types", "The Five Senses",
    "Medical Breakthroughs",
    "The Endocrine System", "The Respiratory System", "The Reproductive System",
    "The Lymphatic System", "The Urinary System", "Medical Imaging",
    "Organ Transplants", "Physical Therapy", "Dentistry", "Optometry",
    "Sports Medicine", "Alternative Medicine", "Medical Ethics",
    "Epidemiology", "Clinical Trials", "Anesthesia", "First Aid",
    "Aging & Longevity", "Sleep Science", "Hormones",
  ],
  "Language & Words": [
    "Etymology", "Idioms & Phrases", "Foreign Languages", "Grammar",
    "Latin & Greek Roots", "English Vocabulary", "Sign Language",
    "Writing Systems", "Slang & Dialects", "Palindromes & Wordplay", "Loanwords",
    "Dead Languages", "Alphabets", "Translation", "Linguistics", "Onomatopoeia",
    "Acronyms & Abbreviations", "Proverbs", "Rhyme & Meter",
    "Constructed Languages",
    "Semantics", "Phonetics", "Syntax", "Historical Linguistics",
    "Language Families", "Bilingualism", "Language Revival",
    "Regional Dialects of English", "Neologisms", "Euphemisms",
    "Homophones & Homographs", "Compound Words", "Word Origins from Latin",
    "Word Origins from Greek", "Portmanteaus", "Language Extinction",
    "Sociolinguistics", "Sign Systems", "Braille", "Morse Code",
  ],
  "Pop Culture & Celebrities": [
    "Award Shows", "Internet Memes", "Celebrity Couples", "Fashion Icons",
    "Viral Moments", "Reality Stars", "Social Media Influencers",
    "Tabloid History", "Red Carpet Fashion", "Celebrity Nicknames",
    "Boy Bands & Girl Groups", "Pop Culture of the 2000s", "Fandoms",
    "Famous Catchphrases", "Celebrity Feuds", "Child Stars",
    "Pop Culture of the 1990s", "Award Season", "Scandals & Paparazzi",
    "Cultural Trends",
    "Talk Show Hosts", "Influencer Marketing", "Celebrity Philanthropy",
    "Celebrity Endorsements", "Celebrity Autobiographies", "Fan Conventions",
    "Celebrity Impersonators", "Viral Challenges", "Meme Culture History",
    "Celebrity Business Ventures", "Awards Show Fashion",
    "Celebrity Rivalries", "Tabloid Magazines", "Social Media Platforms",
    "Celebrity Charities", "Iconic Interviews", "Cultural Icons",
    "Celebrity Weddings", "Celebrity Pets", "Publicist Culture",
  ],
  "Mathematics & Logic": [
    "Arithmetic", "Algebra", "Geometry", "Calculus", "Prime Numbers",
    "Famous Mathematicians", "Probability", "Statistics", "Number Theory",
    "Mathematical Constants", "Logic Puzzles", "Trigonometry", "Fractals",
    "Set Theory", "Pi & Circles", "Mathematical Proofs", "Sequences & Series",
    "Topology", "Game Theory", "Ancient Mathematics",
    "Complex Numbers", "Matrices", "Vectors", "Combinatorics", "Graph Theory",
    "Chaos Theory", "Cryptographic Math", "Mathematical Olympiads",
    "Boolean Algebra", "Differential Equations", "Linear Algebra",
    "Mathematical Puzzles", "Fibonacci Sequence", "Golden Ratio",
    "Infinity Concepts", "Non-Euclidean Geometry",
    "Mathematical Notation History", "Computability Theory",
    "Optimization Problems", "Recreational Mathematics",
  ],
  "Philosophy & Psychology": [
    "Ancient Philosophy", "Ethics", "Logic & Reasoning", "Existentialism",
    "Famous Philosophers", "Cognitive Psychology", "Freud & Psychoanalysis",
    "Metaphysics", "Political Philosophy", "Eastern Philosophy",
    "Behavioral Psychology", "Consciousness", "Epistemology", "Moral Dilemmas",
    "Stoicism", "Social Psychology", "Philosophy of Mind", "Personality Theory",
    "Memory & Learning", "Thought Experiments",
    "Utilitarianism", "Nihilism", "Phenomenology", "Structuralism",
    "Developmental Psychology", "Abnormal Psychology", "Group Psychology",
    "Positive Psychology", "Neuropsychology", "Jungian Psychology",
    "Rationalism vs Empiricism", "Free Will Debates", "Philosophy of Science",
    "Philosophy of Language", "Applied Ethics", "Emotional Intelligence",
    "Cognitive Biases", "Motivation Theory", "Personality Disorders",
    "Philosophy of Religion",
  ],
  "Transportation": [
    "Automobiles", "Aviation", "Trains & Railways", "Ships & Boats",
    "Motorcycles", "Motor Racing", "Space Travel", "Public Transit",
    "Classic Cars", "Aircraft Types", "Bridges & Tunnels", "Bicycles",
    "Electric Vehicles", "Shipping & Ports", "Car Manufacturers",
    "The History of Flight", "Submarines", "Highways & Roads", "Famous Voyages",
    "Engines & Motors",
    "Cargo Shipping", "Air Traffic Control", "Traffic Engineering",
    "High-Speed Rail", "Subway Systems", "Cable Cars", "Off-Road Vehicles",
    "Autonomous Vehicles", "Vehicle Safety", "Fuel Types",
    "Logistics & Freight", "Commercial Aviation", "Helicopters",
    "Hot Air Balloons", "Hovercraft", "Maglev Trains", "Traffic Laws",
    "Vehicle Design", "Transportation History in Cities", "Alternative Fuels",
  ],
  "Nature & Environment": [
    "Weather & Meteorology", "Climate Change", "Natural Disasters", "Ecosystems",
    "Renewable Energy", "Forests", "Coral Reefs", "Rivers & Watersheds",
    "Geology & Rocks", "Minerals & Gems", "Plants & Botany", "Fungi", "Biomes",
    "Pollution", "Conservation", "Soil & Agriculture", "Glaciers & Ice",
    "Earthquakes", "The Water Cycle", "Sustainability",
    "Deforestation", "Ocean Currents", "Biodiversity", "Carbon Cycle",
    "Environmental Policy", "National Wildlife Refuges", "Composting",
    "Water Scarcity", "Air Quality", "Recycling", "Urban Green Spaces",
    "Species Extinction", "Environmental Disasters", "Permaculture",
    "Soil Erosion", "Ozone Layer", "Marine Conservation", "Green Building",
    "Ecotourism", "Environmental Activism",
  ],
  "Games, Hobbies & Curiosities": [
    "Chess", "Card Games", "Board Games", "Puzzles & Riddles", "Playing Cards",
    "Gambling & Casinos", "Magic & Illusions", "Collecting", "Origami",
    "Knitting & Crafts", "Gardening", "Fishing", "Amateur Photography",
    "Astrology & the Zodiac", "Tarot & Fortune Telling", "Comic Books",
    "Quiz & Trivia History", "Toys & Games History", "Tabletop Role-Playing",
    "World Records",
    "Escape Rooms", "Dice Games", "Model Building", "Coin Collecting",
    "Stamp Collecting", "Bird Watching", "Scrapbooking", "Calligraphy",
    "Juggling", "Kite Flying", "Geocaching", "Trivia Nights", "Improv Games",
    "Word Games", "Jigsaw Puzzles", "Cosplay", "Renaissance Fairs",
    "Amateur Radio", "Metal Detecting", "Home Brewing",
  ],
};
