// The subject taxonomy: 25 domains x 20 subjects = 500 subjects.
// Edit this file to change the subject bank, then run `npm run build:seed` to
// regenerate subjects.json and the Supabase seed migration.

module.exports = {
  "World History": [
    "Ancient Egypt", "The Roman Empire", "Ancient Greece", "Medieval Europe",
    "The Renaissance", "World War I", "World War II", "The Cold War",
    "Ancient China", "The Ottoman Empire", "The French Revolution",
    "The American Revolution", "The Industrial Revolution", "Ancient Mesopotamia",
    "The Vikings", "The British Empire", "Feudal Japan", "The Mongol Empire",
    "Pre-Columbian Americas", "The Age of Exploration",
  ],
  "Science & Nature": [
    "Classical Physics", "Quantum Mechanics", "The Periodic Table",
    "Chemical Reactions", "Genetics & DNA", "Evolution", "Cell Biology",
    "Thermodynamics", "Electricity & Magnetism", "Optics & Light",
    "Nuclear Physics", "Organic Chemistry", "Ecology", "Photosynthesis",
    "The Scientific Method", "Famous Scientists", "Nobel Prize Discoveries",
    "States of Matter", "Waves & Sound", "Forces & Motion",
  ],
  "Geography": [
    "World Capitals", "Rivers of the World", "Mountain Ranges", "Oceans & Seas",
    "Deserts", "World Flags", "Countries of Africa", "Countries of Asia",
    "Countries of Europe", "Countries of the Americas", "Islands & Archipelagos",
    "Volcanoes", "National Parks", "U.S. States", "Borders & Boundaries",
    "Lakes of the World", "Climate Zones", "Time Zones", "Cartography & Maps",
    "Population & Cities",
  ],
  "Literature": [
    "Shakespeare", "Greek Classics", "19th-Century Novels", "Modernist Literature",
    "Poetry", "Science Fiction Books", "Fantasy Literature",
    "Detective & Mystery Fiction", "Nobel Laureates in Literature",
    "Children's Literature", "Russian Literature", "American Literature",
    "British Literature", "Dystopian Fiction", "Epic Poetry", "Literary Characters",
    "Opening Lines & Passages", "Banned Books", "Pulitzer & Booker Winners",
    "Playwrights & Drama",
  ],
  "Film & Cinema": [
    "Classic Hollywood", "Oscar Best Pictures", "Film Directors", "Film Noir",
    "Animated Films", "Science Fiction Films", "Horror Films", "Movie Quotes",
    "Blockbuster Franchises", "Foreign Language Films", "The Silent Film Era",
    "Documentary Films", "Movie Soundtracks", "Special Effects & VFX",
    "Cult Classics", "Film Festivals", "Actors & Actresses", "Superhero Movies",
    "Westerns", "Movies by Decade",
  ],
  "Music": [
    "Classical Composers", "The Beatles", "Rock & Roll", "Jazz", "Hip-Hop",
    "Pop Music", "Country Music", "Opera", "Music Theory", "Musical Instruments",
    "Electronic Music", "Grammy Awards", "Music of the 1980s", "Reggae", "Blues",
    "Folk Music", "Broadway & Musicals", "Album Covers", "One-Hit Wonders",
    "World Music",
  ],
  "Sports": [
    "The Olympic Games", "Association Football", "Basketball", "American Football",
    "Baseball", "Tennis", "Golf", "Cricket", "Formula 1", "Boxing",
    "The FIFA World Cup", "Ice Hockey", "Rugby", "Athletics & Track", "Swimming",
    "Cycling", "Martial Arts", "Winter Sports", "Sports Records",
    "Sports Halls of Fame",
  ],
  "Art & Architecture": [
    "Renaissance Art", "Impressionism", "Modern Art", "Famous Paintings",
    "Sculpture", "Gothic Architecture", "Ancient Architecture", "Surrealism",
    "Photography", "Pop Art", "Baroque Art", "Street Art", "Architectural Styles",
    "Famous Museums", "Cubism", "Art Movements", "Pottery & Ceramics",
    "Skyscrapers", "Bridges & Landmarks", "Color & Design",
  ],
  "Technology & Computing": [
    "Computer History", "Programming Languages", "The Internet",
    "Artificial Intelligence", "Operating Systems", "Cybersecurity",
    "Social Media", "Smartphones", "Cryptography", "Video Game Consoles",
    "Tech Companies", "Hardware & Processors", "Databases", "Robotics",
    "The World Wide Web", "Open Source Software", "Silicon Valley",
    "Coding Concepts", "Computer Networking", "Cryptocurrency & Blockchain",
  ],
  "Food & Drink": [
    "World Cuisines", "Wine", "Cheese", "Coffee", "Spices & Herbs", "Desserts",
    "Cocktails", "Beer & Brewing", "Italian Cuisine", "French Cuisine",
    "Asian Cuisine", "Street Food", "Cooking Techniques", "Fruits & Vegetables",
    "Tea", "Baking & Pastry", "Fast Food", "Famous Chefs", "Food History",
    "Condiments & Sauces",
  ],
  "Television": [
    "Sitcoms", "Drama Series", "Reality TV", "Animated Series", "British TV",
    "Game Shows", "Sci-Fi & Fantasy TV", "Crime Dramas", "TV Comedies",
    "Streaming Originals", "Soap Operas", "Talk Shows", "TV Theme Songs", "Anime",
    "TV Catchphrases", "Emmy Winners", "Cartoon Classics", "Miniseries",
    "TV Hosts", "Television History",
  ],
  "Video Games": [
    "Nintendo", "PlayStation", "Retro Arcade Games", "Role-Playing Games",
    "First-Person Shooters", "Indie Games", "Esports", "Game Franchises",
    "Fighting Games", "Strategy Games", "Open-World Games", "The Mario Universe",
    "The Legend of Zelda", "Pokemon", "Minecraft", "Game Developers",
    "Gaming Hardware", "Puzzle Games", "MMORPGs", "Video Game Music",
  ],
  "Mythology & Religion": [
    "Greek Mythology", "Norse Mythology", "Egyptian Mythology", "Roman Mythology",
    "World Religions", "Christianity", "Islam", "Hinduism", "Buddhism", "Judaism",
    "Celtic Mythology", "Japanese Folklore", "Legendary Creatures",
    "Biblical Stories", "Gods & Goddesses", "Sacred Texts", "Mythological Heroes",
    "Afterlife Beliefs", "Rituals & Festivals", "Creation Myths",
  ],
  "Politics & Law": [
    "World Leaders", "U.S. Presidents", "Political Systems", "The United Nations",
    "Constitutions", "Elections & Voting", "Supreme Court Cases",
    "International Treaties", "Human Rights", "Political Ideologies", "Monarchies",
    "Diplomacy", "Legal Systems", "Famous Trials", "Political Scandals",
    "Prime Ministers", "Revolutions & Movements", "Branches of Government",
    "Espionage", "Landmark Legislation",
  ],
  "Business & Economics": [
    "Stock Markets", "Famous Entrepreneurs", "Global Brands", "Economic Theory",
    "Currencies", "Marketing & Advertising", "Startups", "Banking",
    "Trade & Commerce", "Fortune 500 Companies", "Supply & Demand",
    "Inflation & Recession", "Corporate Logos", "Billionaires",
    "Management & Leadership", "Real Estate", "Mergers & Acquisitions",
    "Retail & Shopping", "Economic History", "Personal Finance",
  ],
  "Space & Astronomy": [
    "The Solar System", "The Planets", "Stars & Constellations", "Galaxies",
    "Space Missions", "The Moon", "Black Holes", "The Sun", "Astronauts",
    "Telescopes", "Comets & Asteroids", "NASA", "The Big Bang", "Exoplanets",
    "Rockets & Spaceflight", "Mars Exploration", "The Space Station", "Cosmology",
    "Nebulae", "Space Agencies",
  ],
  "Animals & Wildlife": [
    "Mammals", "Birds", "Reptiles & Amphibians", "Fish & Marine Life", "Insects",
    "Dinosaurs", "Endangered Species", "Big Cats", "Primates", "Ocean Predators",
    "Pets & Domestic Animals", "Animal Behavior", "Migration & Hibernation",
    "Rainforest Animals", "Polar Wildlife", "Venomous Animals",
    "Animal Classification", "Extinct Animals", "Deep Sea Creatures",
    "Wildlife Conservation",
  ],
  "Human Body & Medicine": [
    "Human Anatomy", "The Circulatory System", "The Nervous System",
    "The Immune System", "Diseases & Disorders", "Vaccines", "Medical History",
    "Surgery", "Pharmacology", "Nutrition", "The Brain", "Genetics & Heredity",
    "Bones & Skeleton", "The Digestive System", "Mental Health", "Pandemics",
    "Famous Physicians", "Blood & Blood Types", "The Five Senses",
    "Medical Breakthroughs",
  ],
  "Language & Words": [
    "Etymology", "Idioms & Phrases", "Foreign Languages", "Grammar",
    "Latin & Greek Roots", "English Vocabulary", "Sign Language",
    "Writing Systems", "Slang & Dialects", "Palindromes & Wordplay", "Loanwords",
    "Dead Languages", "Alphabets", "Translation", "Linguistics", "Onomatopoeia",
    "Acronyms & Abbreviations", "Proverbs", "Rhyme & Meter",
    "Constructed Languages",
  ],
  "Pop Culture & Celebrities": [
    "Award Shows", "Internet Memes", "Celebrity Couples", "Fashion Icons",
    "Viral Moments", "Reality Stars", "Social Media Influencers",
    "Tabloid History", "Red Carpet Fashion", "Celebrity Nicknames",
    "Boy Bands & Girl Groups", "Pop Culture of the 2000s", "Fandoms",
    "Famous Catchphrases", "Celebrity Feuds", "Child Stars",
    "Pop Culture of the 1990s", "Award Season", "Scandals & Paparazzi",
    "Cultural Trends",
  ],
  "Mathematics & Logic": [
    "Arithmetic", "Algebra", "Geometry", "Calculus", "Prime Numbers",
    "Famous Mathematicians", "Probability", "Statistics", "Number Theory",
    "Mathematical Constants", "Logic Puzzles", "Trigonometry", "Fractals",
    "Set Theory", "Pi & Circles", "Mathematical Proofs", "Sequences & Series",
    "Topology", "Game Theory", "Ancient Mathematics",
  ],
  "Philosophy & Psychology": [
    "Ancient Philosophy", "Ethics", "Logic & Reasoning", "Existentialism",
    "Famous Philosophers", "Cognitive Psychology", "Freud & Psychoanalysis",
    "Metaphysics", "Political Philosophy", "Eastern Philosophy",
    "Behavioral Psychology", "Consciousness", "Epistemology", "Moral Dilemmas",
    "Stoicism", "Social Psychology", "Philosophy of Mind", "Personality Theory",
    "Memory & Learning", "Thought Experiments",
  ],
  "Transportation": [
    "Automobiles", "Aviation", "Trains & Railways", "Ships & Boats",
    "Motorcycles", "Motor Racing", "Space Travel", "Public Transit",
    "Classic Cars", "Aircraft Types", "Bridges & Tunnels", "Bicycles",
    "Electric Vehicles", "Shipping & Ports", "Car Manufacturers",
    "The History of Flight", "Submarines", "Highways & Roads", "Famous Voyages",
    "Engines & Motors",
  ],
  "Nature & Environment": [
    "Weather & Meteorology", "Climate Change", "Natural Disasters", "Ecosystems",
    "Renewable Energy", "Forests", "Coral Reefs", "Rivers & Watersheds",
    "Geology & Rocks", "Minerals & Gems", "Plants & Botany", "Fungi", "Biomes",
    "Pollution", "Conservation", "Soil & Agriculture", "Glaciers & Ice",
    "Earthquakes", "The Water Cycle", "Sustainability",
  ],
  "Games, Hobbies & Curiosities": [
    "Chess", "Card Games", "Board Games", "Puzzles & Riddles", "Playing Cards",
    "Gambling & Casinos", "Magic & Illusions", "Collecting", "Origami",
    "Knitting & Crafts", "Gardening", "Fishing", "Amateur Photography",
    "Astrology & the Zodiac", "Tarot & Fortune Telling", "Comic Books",
    "Quiz & Trivia History", "Toys & Games History", "Tabletop Role-Playing",
    "World Records",
  ],
};
